### ISSUE TITLE
Transparent PNGs and GIFs have black background when using the image tag

### ISSUE THREAD

**Issue by samkuehn** [zopefoundation/z3c.rml#32]
```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE document SYSTEM "rml.dtd">
<document filename="imagetest.pdf">
  <pageDrawing>
    <image file="https://www.google.com/images/srpr/logo11w.png" x="1in" y="2in" height="1in" width="2in" preserveAspectRatio="1"/>
  </pageDrawing>
</document>
```
Produces
![screen shot 2015-02-04 at 4 54 55 pm](https://cloud.githubusercontent.com/assets/263189/6052317/90343486-ac8e-11e4-9f2d-fc6adae4cf3a.png)

The img tag works as expected.  The problem is that I need to use the image tag in the pageGraphics section of the template.

**Comment by kylemacfarlane** [comment]
I fixed this over in my python 3 branch at #27.

A lot more fixes than just python 3 support are ending up in the branch. They really should be their own pull requests but I don't want to be fixing stuff on top of the old py2 only code.

**Comment by samkuehn** [comment]
Thanks @kylemacfarlane worked perfectly.  Would you mind if I packaged these changes up into their own PR?

**Comment by kylemacfarlane** [comment]
You can create a PR but none of the committers have really been around for six months so when they do come back both PRs would probably get merged at the same time anyway.

Last time I had a bunch of PRs about 2-3 years ago they asked me to try and join the Zope organisation so I could merge my own commits, but I never looked into it and doubt they'd accept me anyway since this is the only Zope package I use and the organisation has access to many more.

**Comment by samkuehn** [comment]
Thanks @kylemacfarlane I think I will hold off on creating the PR and just pull from my fork until your PR is merged and a new version is released on PyPi.
