### ISSUE TITLE
Zope independency

### ISSUE THREAD

**Issue by tieugene** [zopefoundation/z3c.rml#86]
How hard to make subj as zope-independent?
Without importing zope.interface etc zope.* in most of files.
An idea is to use subj in other applications outside zope world without zope.* footprints.

**Comment by regebro** [comment]
It works just fine outside the zope world. It's using a few zope.* packages, that's all. The footprint isn't large at all.

**Comment by tieugene** [comment]
> The footprint isn't large at all.
Well, I think 32957 lines of required zope.* against 11791 lines of z3c.rml itself is not "isn't large".
(macOS Catalina, brew, py39)

**Comment by jugmac00** [comment]
You can use https://github.com/romanlv/trml2pdf if you insist on as few external dependencies as possible. However, the mentioned repository is not very active.

**Comment by tieugene** [comment]
> You can use https://github.com/romanlv/trml2pdf

I [use](https://github.com/tieugene/trml2pdf) it, but it seems really not active.
Z3c.rml seems more "production ready".
And adding letterBoxes (that I need) to z3c.rml is more preferable then making trml2pdf really usable.

**Comment by regebro** [comment]
I don't really see how lines of code is a relevant metric here. It doesn't add any problems for you that some of the functionality is in external packages. z3c.rml only includes three zope packages: interfaces, schema and events.
It also installs pygments, reportlab, setuptools and lxml as well, which are just as large, or larger.

z3c.rml: 18576

zope.event:  60 loc
zope.schema: 6758 loc
zope.interface: 15111 loc
lxml: 21647 loc
setuptools: 23351 loc
reportlab: 57925 loc
pygments: 74243 loc

In total, after installing z3c.rml in a virtualenv my site packages has 315315 lines of code in it. Why would 23000 of them drive you away just because the package name starts with zope? They are just packages. There's nothing special with them. They aren't particularly large. They serve a useful function.
